### ISSUE TITLE
VS 2019 :  This extension is not installable on any currently installed products

### ISSUE THREAD

**Issue by pouyaSamie** [lkytal/BuiltinCmd#17]
Hi Im facing an error when i try to install the extention from market place 

**Windows 10 version 1909 (OS Build : 18363.476)
Visual studio Version : 16.3.10**

here is the full log :

12/11/2019 3:20:58 PM - Microsoft VSIX Installer
12/11/2019 3:20:58 PM - -------------------------------------------
12/11/2019 3:20:58 PM - Initializing Install...
12/11/2019 3:20:58 PM - Extension Details...
12/11/2019 3:20:58 PM - 	Identifier      : 5f1a1460-a418-4fae-9cad-ff1c76b7aed9
12/11/2019 3:20:58 PM - 	Name            : BuiltinCmd
12/11/2019 3:20:58 PM - 	Author          : Lkytal
12/11/2019 3:20:58 PM - 	Version         : 2.1.0
12/11/2019 3:20:58 PM - 	Description     : Integrate CMD Terminal into VS2013, VS2015, VS2017 or VS2019
12/11/2019 3:20:58 PM - 	Locale          : en-US
12/11/2019 3:20:58 PM - 	MoreInfoURL     : 
12/11/2019 3:20:58 PM - 	InstalledByMSI  : False
12/11/2019 3:20:58 PM - 	SupportedFrameworkVersionRange : [4.5,)
12/11/2019 3:20:58 PM - 
12/11/2019 3:20:58 PM - 	Supported Products : 
12/11/2019 3:20:58 PM - 		Microsoft.VisualStudio.Pro
12/11/2019 3:20:58 PM - 			Version : [12.0,17.0)
12/11/2019 3:20:58 PM - 		Microsoft.VisualStudio.Community
12/11/2019 3:20:58 PM - 			Version : [12.0,17.0)
12/11/2019 3:20:58 PM - 		Microsoft.VisualStudio.Enterprise
12/11/2019 3:20:58 PM - 			Version : [12.0,17.0)
12/11/2019 3:20:58 PM - 
12/11/2019 3:20:58 PM - 	References      : 
12/11/2019 3:20:58 PM - 		-------------------------------------------------------
12/11/2019 3:20:58 PM - 		Identifier   : Microsoft.VisualStudio.MPF.12.0
12/11/2019 3:20:58 PM - 		Name         : Visual Studio MPF 12.0
12/11/2019 3:20:58 PM - 		Version      : [12.0,17.0)
12/11/2019 3:20:58 PM - 		MoreInfoURL  : 
12/11/2019 3:20:58 PM - 		Nested       : No
12/11/2019 3:20:58 PM - 
12/11/2019 3:20:58 PM - 
12/11/2019 3:20:58 PM - Searching for applicable products...
12/11/2019 3:20:58 PM - Found installed product - Global Location
12/11/2019 3:20:58 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by michaelm7456** [comment]
Just done a fresh install of this Extension on my local instance of Visual Studio 2019 and it looks to have installed successfully.

Microsoft Visual Studio Community 2019
Version: 16.6.4

![image](https://user-images.githubusercontent.com/20442719/87973466-75f8e980-cac0-11ea-935e-f20a8644e349.png)

I did encounter a similar issue a while back when trying to port an Extension forward from VS 2017 to VS 2019, and had to install the 'Visual Studio extension development' workload to allow the installation to complete fully.

https://stackoverflow.com/questions/54382367/visual-studio-extension-installation-cannot-find-setup-engine-instance/56001724#56001724

Failing this I would suggest re-installing your instance of Visual Studio, as there may be some minor environmental issue that is causing this problem.

Hope this helps!

**Comment by astrohart** [comment]
I suggest the extension should not need to have the extensibility workload installed just to successfully install.  Ideally, it should not have that as a dependency.
